//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pakizin.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PakizinEntities : DbContext
    {
        public PakizinEntities()
            : base("name=PakizinEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tbl_ability> tbl_ability { get; set; }
        public virtual DbSet<tbl_education> tbl_education { get; set; }
        public virtual DbSet<tbl_experience> tbl_experience { get; set; }
        public virtual DbSet<tbl_portfolio> tbl_portfolio { get; set; }
        public virtual DbSet<tbl_post> tbl_post { get; set; }
        public virtual DbSet<tbl_skill> tbl_skill { get; set; }
        public virtual DbSet<tbl_user> tbl_user { get; set; }
    }
}
