//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pakizin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_education
    {
        public int Id { get; set; }
        public string Scala { get; set; }
        public string Description { get; set; }
    }
}
